# Generated by Django 5.1.6 on 2025-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('like', models.IntegerField(default=0)),
                ('pdf', models.FileField(upload_to='books/pdf')),
            ],
        ),
    ]
