# Generated by Django 5.1.6 on 2025-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Want to Read', 'Want to Read'), ('Reading', 'Reading'), ('Finished', 'Finished'), ('Not Read', 'Unread')], default='Not Read', max_length=25),
        ),
    ]
